#!/bin/sh
#
# Start iwd at boot
#

case "$1" in
    start)
        echo "Starting iwd..."
        iwd &
        ;;
    stop)
        echo "Stopping iwd..."
        killall iwd
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
